title: Palm
description: ğŸŒ´ Outdoor BLE-connected UV sensor keychain ğŸ—
url: "https://hutscape.com/palm"
parent: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/hutscape/palm
  raw_content_url: https://raw.githubusercontent.com/hutscape/palm/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "scripts"]
include: ["_data"]
collections:
  code:
    output: true
    permalink: /code/:name

project:
  power: LiPO
  wireless: BLE
  mcu: nRF52
  sensor: UV Index
  ota: No
  battery-life: 5 days
  bom-uniq: 10
  bom-total: 13
  bom-cost-sgd: 68.64
  bom-cost-usd: 50.47
  vendors: 4
  schedule: 3 months
  status: completed
  completion: July 2019
