title: Palm
description: ğŸŒ´ Get alerted on excessive UV radiation with a backpack keychain ğŸ—
url: "https://hutscape.com/palm"
markdown: kramdown
permalink: /:title
google_analytics: UA-XXXXX-Y
github:
  repository_url: https://github.com/hutscape/palm
